version: 2

models:
  - name: articles
    columns:
      - name: site_id
        description: Unique identifier for the site
        tests:
          - not_null
        type: string
      - name: article_id
        description: Unique identifier for the article
        tests:
          - not_null
        type: string
      - name: title
        description: Article title
        tests:
          - not_null
        type: string
      - name: author
        description: Article author
        tests:
          - not_null
        type: string
      - name: author_id
        description: Unique identifier for the author
        tests:
          - not_null
        type: string
      - name: category
        description: Article category
        tests:
          - not_null
        type: string
      - name: published_date
        description: Date when the article was published
        tests:
          - not_null
        type: date
      - name: created_at
        description: Timestamp when the record was created
        tests:
          - not_null
        type: timestamp
  - name: articles_hourly
    columns:
      - name: site_id
        description: Unique identifier for the site
        tests:
          - not_null
        type: string
      - name: article_id
        description: Unique identifier for the article
        tests:
          - not_null
        type: string
      - name: page_views
        description: Number of page views
        tests:
          - not_null
        type: integer
      - name: new_users
        description: Number of new users
        tests:
          - not_null
        type: integer
      - name: bounce_rate
        description: Bounce rate
        tests:
          - not_null
        type: decimal
      - name: pageviews_per_session
        description: Average page views per session
        tests:
          - integer
        type: decimal
      - name: session_per_user
        description: Average sessions per user
        tests:
          - not_null
        type: integer
      - name: users
        description: Number of unique users
        tests:
          - not_null
        type: integer
      - name: period_date
        description: Date period
        tests:
          - not_null
        type: date
      - name: hour
        description: Hour of the day
        tests:
          - not_null
        type: integer
      - name: attention_time
        description: Total attention time
        tests:
          - not_null
        type: integer
      - name: created_at
        description: Timestamp when the record was created
        tests:
          - not_null
        type: timestamp
      - name: time_of_day
        description: Time of day
        tests:
          - not_null
        type: string
      - name: frequency
        description: Frequency
        tests:
          - not_null
        type: string
      - name: key_words
        description: List of key words
        tests:
          - not_null
        type: string
      - name: exit_page_distribution
        description: Distribution of exit pages
        tests:
          - not_null
        type: string
      - name: referrer_distribution
        description: Distribution of referrers
        tests:
          - not_null
        type: string
      - name: country_distribution
        description: Distribution of countries
        tests:
          - not_null
        type: string
