// Explore edit
const ExploreUpdate = {
  UPDATE_QUERY_SHARE: "UPDATE_QUERY_SHARE",
  UPDATE_DASHBOARD_SHARE: "UPDATE_DASHBOARD_SHARE",
  UPDATE_QUERY: "UPDATE_QUERY",
  UPDATE_QUERYINFO: "UPDATE_QUERYINFO"
};

export default ExploreUpdate;
