// Pipeline edit
const PipelineEditActionTypes = {
  UPDATE_ACTIVEMENU: "UPDATE_ACTIVEMENU",
  UPDATE_DESTINATION: "UPDATE_DESTINATION",
  UPDATE_PIPELINEID: "UPDATE_PIPELINEID",
  UPDATE_REDIRECTURL: "UPDATE_REDIRECTURL",
  UPDATE_CONNECTIONS: "UPDATE_CONNECTIONS",
};

export default PipelineEditActionTypes;
