// Sidebar ActionType

const SidebarActionTypes = {
  UPDATE_SIDEBARMENU: "UPDATE_SIDEBARMENU",
  UPDATE_QUERY_SIDEBARMENU: "UPDATE_QUERY_SIDEBARMENU",
  UPDATE_QUERY_SIDEBARMAINMENU: "UPDATE_QUERY_SIDEBARMAINMENU",
  REFRESH_SIDEBARMENU: "REFRESH_SIDEBARMENU",
  QUERY_FOLDER_UPDATE: "QUERY_FOLDER_UPDATE",
};

export default SidebarActionTypes;
